# Read the documentation: https://github.com/acseo/TypesenseBundle/blob/master/README.md
acseo_typesense:
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
        # Optional : add prefix to all collection names in Typesense
        #collection_prefix: 'app_'
    # Collection settings
    collections:
        user:
            entity: 'App\Entity\User'              # Doctrine Entity class
            fields:
                    id: # Entity attribute name
                        name: id                # Typesense attribute name
                        type: primary                  # Attribute type
                    nom:
                        name: nom
                        type: string
            default_sorting_field : id