# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
  configs:
    main_config:
      language: fr
      toolbar: full
      filebrowserBrowseRouteParameters: [ instance: "ckeditor" ]
      filebrowserBrowseRoute: "elfinder"
