# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        odpfFichiersPasses:
            properties:
                nomfichier: ~
                equipepassee : ~
                typefichier : ~
                editionspassees : ~


            persistence:
                driver: orm
                model: App\Entity\Odpf\OdpfFichierspasses
