# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        fichierspasses:
            properties:
                nomfichier: ~
                typefichier: [0,1,2,5]
            persistence:
                driver: orm
                model: App\Entity\Odpf\OdpfFichierspasses
