# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:

    default_manager: mongodb
    clients:
        default:  { host: localhost, port: 8000}

    indexes:
        user:
            persistence:
                driver: orm
                model: App\Entity\User
                finder: ~
                provider: ~
            properties:
                nom: ~










