# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
  configs:
    default:
      language: fr
      toolbar: full
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: [ ]

    main_config:
      language: fr
      toolbar: full


