# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:  { host: localhost, port: 8000 }
    indexes:
        odpfFichierspasses:
            serializer:
                groups: [ elastica ]
            persistence:
                driver: orm
                model: App\Entity\Odpf\OdpfFichierspasses
                finder: ~
                provider: ~
            properties:
                nomfichier: ~


