when@dev:
<<<<<<< HEAD
  _errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error
=======
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
>>>>>>> 3f64d87 (Add initial set of files)
