<?php

namespace App\Repository;

/**
 * ElevesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. cope coller
 */
class ElevesRepository extends \Doctrine\ORM\EntityRepository
{

}


