<?php

namespace App\Repository;

/**
 * CadeauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. Copier coller de visites
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

}

