<?php

namespace App\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * JuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuresRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(JuresRepository $jr): querybuilder
    {
        return $jr->createQueryBuilder('j')->select('j');


    }

}


