<?php

namespace App\Repository;

/**
 * LiaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. Copier coller de visites
 */
class LiaisonRepository extends \Doctrine\ORM\EntityRepository
{

}



