<?php

namespace App\Repository;

/**
 * PhrasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhrasesRepository extends \Doctrine\ORM\EntityRepository
{
}