<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * PrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixRepository extends EntityRepository
{
    public static function getListPrix(PrixRepository $pr): QueryBuilder
    {

        return $pr->createQueryBuilder('p')->select('p');
        //->where('p.classement = :classement')
        //->setParameter('classement',$classement);


    }

    /**
     * @throws NonUniqueResultException
     * @throws NoResultException
     */
    public function getNbrePrix($niveau)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('count(p.id)');
        $qb->where('p.niveau = :niveau');
        $qb->setParameter('niveau', $niveau);

        return $qb->getQuery()->getSingleScalarResult();
    }

}