<?php

namespace App\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * TotalequipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. cope coller
 */
class TotalequipesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotEquipesNom($lettre)
    {
        $query = $this->createQueryBuilder('e')
            ->select('e.nomEquipe')
            ->where('e.lettreEquipe=:lettre')
            ->setParameter('lettre', $lettre);

        return $query->getQuery()->getResult();
    }

    public function getEquipeNa(TotalequipesRepository $er): QueryBuilder
    {

        return $er->createQueryBuilder('e')->select('e')
            ->orderBy('e.lettreEquipe', 'ASC');


    }
}
